### ISSUE TITLE
GPLv3 License Compliance

### ISSUE THREAD

**Issue by Conzar** [covermymeds/puppet-pgbouncer#2]
Can you please change the license back to GPLv3 as the original source was under this license.  The GPLv3 prohibits a license change.

Thank you

**Comment by cjestel** [comment]
I have a branch that I'm working on now that will revert the license to GPLv3 as well as apply some additional error checking and fix some of the puppet-lint warnings. It should go out within the next couple of days.

Thanks!

**Comment by cjestel** [comment]
https://github.com/covermymeds/puppet-pgbouncer/pull/3 has been merged to master and I am in the process of tagging the release and pushing to the forge. Thank you for your feedback.

**Comment by Conzar** [comment]
Thank you @cjestel !  I have been very busy this past week due to some ramp up on a new project.  Will hopefully look into the code changes soon.
