### ISSUE TITLE
module broken when using concat module 2+

### ISSUE THREAD

**Issue by madeddie** [covermymeds/puppet-pgbouncer#20]
On my ubuntu 14.10 clients running puppet 3.8.6 both

```
 File[$userlist_file]
 File[$userlist_file, $conffile]
```

in the init.pp do not work. The error that I get is:

> Failed to apply catalog: Could not find dependent File[/etc/pgbouncer/userlist.txt] for File[/etc/default/pgbouncer] at /etc/puppet/environments/production/modules/pgbouncer/manifests/init.pp:146

If I replace "File" with "Concat" it solves the problem.
I'm not sure if the concat module should take care of this or if I'm doing something else wrong.

The first failure could be Debian/Ubuntu specific, but the second time it's executed for all OS families.

**Comment by madeddie** [comment]
Apparently this has stopped working with concat module since version 2. Could you fix this? If you would like a PR (would be tiny :)) let me know.

**Comment by cjestel** [comment]
I don't have ubuntu installed anywhere to test offhand. If you can do a PR I can test it with our setup and make sure there are no issues.

**Comment by madeddie** [comment]
It's no longer just an ubuntu issue, it's a problem with concat module past version 2.
