### ISSUE TITLE
GPLv3 License Violation

### ISSUE THREAD

**Issue by Conzar** [covermymeds/puppet-pgbouncer#7]
The original init.pp file has the GPLv3 license assigned to it.

```
# === Copyright
#
# GPL-3.0+
```

You are violating the GPL by changing it to

```
# === Copyright
#
# CoverMyMeds
#
# === License
#
# MIT License (MIT)
#
```

Please revert the changes back to the original license within the source code.  As the entire project is GPLv3, you must adher to this license.  You cannot legally use the MIT license.

Thank you for your cooperation.

**Comment by cjestel** [comment]
Sorry I missed this when I changed the license back elsewhere. This will get fixed with the next update which should occur in the next couple of weeks.

**Comment by Conzar** [comment]
Thank you!

**Comment by cjestel** [comment]
https://github.com/covermymeds/puppet-pgbouncer/pull/11 resolves this issue. I'm publishing the new release today.
